version: '2'

services:
  db:
    container_name: nau.wordpress.devstack.db
    image: mysql:5.6
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "127.0.0.1:10001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      #MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password

  wordpress:
    container_name: nau.wordpress.devstack.wordpress
    depends_on:
      - db
    image: wordpress:5.7.0-php7.4-fpm
    volumes:
      - ./php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./wp-content:/var/www/html/wp-content
      - wp_data:/var/www/html
      - ../wp-nau-theme:/var/www/html/wp-content/themes/wp-nau-theme
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME','http://localhost');
        define('WP_SITEURL','http://localhost');
        define('WP_ALLOW_MULTISITE', true);
        define('MULTISITE', true);
        define('SUBDOMAIN_INSTALL', false);
        define('DOMAIN_CURRENT_SITE', 'localhost');
        define('PATH_CURRENT_SITE', '/');
        define('SITE_ID_CURRENT_SITE', 1);
        define('BLOG_ID_CURRENT_SITE', 1);
        define('WP_DEBUG', true);

  nginx:
    container_name: nau.wordpress.devstack.nginx
    image: nginx:latest
    # networks:
    #   frontend:
    restart: always
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./wp-content:/var/www/html/wp-content
      - wp_data:/var/www/html
      - ../wp-nau-theme:/var/www/html/wp-content/themes/wp-nau-theme
    depends_on:
      - wordpress

  wordpress_watcher:
    command: bash -c 'cd /usr/src/app ; gulp build; gulp'
    container_name: nau.wordpress.devstack.watcher
    build: ../wp-nau-theme
    volumes:
      - ../wp-nau-theme:/usr/src/app

volumes:
  wp_data:
